- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories
      package: update_cache=yes
      changed_when: False
  
  tasks:
  - name: Install pandoc
    package: name={{item}}
    with_items:
      - pandoc
      - htop
      - gnome-boxes
