- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories
      package: update_cache=yes
      changed_when: False
  
  tasks:
  - include-tasks: tasks/packages.yml
  - include-tasks: tasks/python.yml
  - include-tasks: tasks/users.yml
  - include-tasks: tasks/cron.yml
  - include-tasks: tasks/directories.yml
