- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories
      package: update_cache=yes
      changed_when: False
  
  tasks:
  - include: tasks/packages.yml
  - include: tasks/python.yml
  - include: cron.yml
  - include: users.yml
