- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories
      package: update_cache=yes
      changed_when: False
  
  tasks:
  - include_tasks: tasks/packages.yml
  - include_tasks: tasks/python.yml
  - include_tasks: tasks/users.yml
  - include_tasks: tasks/cron.yml
  - include_tasks: tasks/directories.yml

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
