- name: install cron job (ansible-pull)
  become: true
  cron:
    user: "ansible"
    name: "ansible provision"
    minute: "0"
    hour:  "*"
    job: "/usr/bin/ansible-pull -o -U https://github.com/birgens/configuration.git >> /var/log/ansible-pull.log 2>&1"
