- name: Install cron job for ansible-pull
  become: true
  cron:
    name: "Ansible Provision"
    minute: "0"
    hour: "*"
    user: "ansible"
    job: "/usr/bin/ansible-pull -o -U https://github.com/birgens/configuration.git >> /var/log/ansible-pull.log 2>&1"
    cron_file: "ansible_pull_cron"
    state: present
