- name: Install python
  package: name={{item}}
  with_items:
    - python3
    - python-is-python3
    - python3-pip

- name: Install common packages
  ansible.builtin.pip:
    name:
      - matplotlib
      - numpy
      - pandas
      - jupyter
      - seaborn
