- name: Install writing packages
  package: name={{item}}
  with_items:
    - pandoc
    - git
    - emacs
    - "{{ latex }}"
    - pdf2svg
    
- name: Install flatpaks (Zotero)
  community.general.flatpak:
    name: org.zotero.Zotero
