- name: Add emacs repo into sources list
  ansible.builtin.apt_repository:
    repo: ppa:kelleyk/emacs

- name: Install writing packages
  package:
    name: "{{item}}"
  loop:
    - pandoc
    - emacs29-nativecomp
    - "{{ latex }}"
    - pdf2svg

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpaks (Zotero)
  community.general.flatpak:
    name: org.zotero.Zotero

- name: Install Doom requirements
  package:
    name: "{{item}}"
  loop:
    - ripgrep
    - fd-find

